{% set name = "mplotutils" %}
{% set version = "0.7.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mplotutils-{{ version }}.tar.gz
  sha256: 0204c2231493fd19892d09a917e60755a6cbce4eed186917c4e3100f24b304d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=7.0
    - pip
  run:
    - python >={{ python_min }}
    - cartopy >=0.23
    - matplotlib-base >=3.9
    - numpy >=1.26
    - packaging >=23.1
    - shapely >=2.0
    - xarray >=2024.7
  run_constrained:
    - seaborn >=0.13

test:
  imports:
    - mplotutils
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mpytools/mplotutils
  summary: utilities for matplotlib and cartopy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mathause
